version: '3.7'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application
    ports:
      - 5454:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 5455:8080

volumes:
  postgres:
